from typing import Protocol


class MarketDataProvider(Protocol):
    def latest_price(self, ticker: str) -> float: ...
    def bars(self, ticker: str, limit: int = 50) -> list[dict]: ...
    def gainers(self, limit: int) -> list[dict]: ...


class NewsProvider(Protocol):
    def news(self, ticker: str, limit: int = 5) -> list[dict]: ...
